[project]
name = "kb-sdk-plus"
version = "0.1.0"
description = "KB-SDK but +"
readme = "README.md"
requires-python = "==3.8.10"
dependencies = [
    "jsonrpcbase>=0.2.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ipython>=8.12.3",
    "pytest>=8.3.5",
    "pytest-cov>=5.0.0",
]
